### ISSUE TITLE
Getting Started Instructions Unclear

### ISSUE THREAD

**Issue by ghost** [jamesmawm/IB-Trading-Models-And-Backtester#1]
Your 3rd line references self before it is defined.  Please clarify. 
3rd line reads:
self.ibhft.start_data_stream(self.on_started, self.on_tick , STOCKS_TO_STREAM, self.on_position_changed)

**Comment by jamesmawm** [comment]
The 3 lines are an example of of getting started; it should be run from a method within your self-contained class. See https://github.com/jamesmawm/IB-Trading-Models-And-Backtester/blob/master/src/Strat-Empty.py for a full example of getting started.

**Comment by ghost** [comment]
Great, I have the code up and running now, thanks!
